apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "web-config.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-config.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-config.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetport }}
            # - containerPort: 3000